Fixed problem with pipe fails and error code checking

diff --git a/tutorsh b/tutorsh
--- a/tutorsh
+++ b/tutorsh
@@ -6,7 +6,7 @@
 # at foreign source code.
 
 PROG="${0##*/}"
-VERSION="1.2"
+VERSION="1.3"
 
 
 ##
@@ -293,8 +293,13 @@ fi
 cd "$BASE"
 
 # start at the least immatricualation number if nothing else specified
+set -o pipefail
 if [ -z "$immno" ]; then
-	immno=`ls -d 1* | head -n 1` || exit 23
+	immno=`ls -d 1* | head -n 1`
+	if [ $? -ne 0 ]; then
+		echo "Cannot find matriculation directories" >&2
+		exit 23
+	fi
 fi
 
 next="$immno/$postPath"
